POST https://anph.xyz/register
Content-Type: application/json

{
  "email": "aanltll2992@gmail.com",
  "password": "123456",
  "confirmPassword": "123456",
  "phoneNumber":"0912345678"
}

###

GET https://anph.xyz/active?t=7%2FWNpDMp5FC7%2BLNOzt7zBBihkYDZDu2tmfrzVSIefcFkI0j7heXUvsbRqgo3RDU9DZuKsSLOjHlWu8uWlTXTURThwUCmd9sLEy%2FJbXK6YReUzURvup6OXjAbrhBSHwaw
Content-Type: application/json

###

POST https://anph.xyz/login
Content-Type: application/json

{
  "email": "aanltll2992@gmail.com",
  "password": "123456"
}

###

DELETE https://anph.xyz/logout
Content-Type: application/json

{
  "email": "aanltll2992@gmail.com"
}

###

DELETE https://anph.xyz/delete_account
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQwZWU2OTQ0YzRlMjcxMmIwMmRiOTg2YzI0MTRkNWQxIiwiZW1haWwiOiJhYW5sdGxsMjk5MkBnbWFpbC5jb20iLCJwaG9uZU51bWJlciI6IjA5MTIzNDU2NzgiLCJwYXNzd29yZCI6ImUxMGFkYzM5NDliYTU5YWJiZTU2ZTA1N2YyMGY4ODNlIiwiYWN0aXZlIjp0cnVlLCJpYXQiOjE2NDMyNzgxOTUsImV4cCI6MTY0MzI4MTc5NX0.mQVJ6SgFKNaBVjRDUbVCQCfruIIaJ6tDuaKGOaFNaJ0

{
  "email": "aanltll2992@gmail.com"
}


###

POST https://anph.xyz/token
Content-Type: application/json

{
  "email":"aanltll2992@gmail.com",
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQwZWU2OTQ0YzRlMjcxMmIwMmRiOTg2YzI0MTRkNWQxIiwiZW1haWwiOiJhYW5sdGxsMjk5MkBnbWFpbC5jb20iLCJwaG9uZU51bWJlciI6IjA5MTIzNDU2NzgiLCJwYXNzd29yZCI6ImUxMGFkYzM5NDliYTU5YWJiZTU2ZTA1N2YyMGY4ODNlIiwiYWN0aXZlIjp0cnVlLCJpYXQiOjE2NDMyNzgxOTV9.6dzLusOowsi-hHEdAmmVHBJ4nB_Xzdo6TCEm_XTfaDA"
}

###

POST https://anph.xyz/user_detail
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQwZWU2OTQ0YzRlMjcxMmIwMmRiOTg2YzI0MTRkNWQxIiwiZW1haWwiOiJhYW5sdGxsMjk5MkBnbWFpbC5jb20iLCJwaG9uZU51bWJlciI6IjA5MTIzNDU2NzgiLCJwYXNzd29yZCI6ImUxMGFkYzM5NDliYTU5YWJiZTU2ZTA1N2YyMGY4ODNlIiwiYWN0aXZlIjp0cnVlLCJpYXQiOjE2NDMyNzgxOTUsImV4cCI6MTY0MzI4MTc5NX0.mQVJ6SgFKNaBVjRDUbVCQCfruIIaJ6tDuaKGOaFNaJ0



{
  "email": "aanltll2992@gmail.com"
}


###

POST https://anph.xyz/analytics
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQwZWU2OTQ0YzRlMjcxMmIwMmRiOTg2YzI0MTRkNWQxIiwiZW1haWwiOiJhYW5sdGxsMjk5MkBnbWFpbC5jb20iLCJwaG9uZU51bWJlciI6IjA5MTIzNDU2NzgiLCJwYXNzd29yZCI6ImUxMGFkYzM5NDliYTU5YWJiZTU2ZTA1N2YyMGY4ODNlIiwiYWN0aXZlIjp0cnVlLCJpYXQiOjE2NDMyNzgxOTUsImV4cCI6MTY0MzI4MTc5NX0.mQVJ6SgFKNaBVjRDUbVCQCfruIIaJ6tDuaKGOaFNaJ0


{
  "view_id": "259241289"
}