POST https://anph.xyz/register
Content-Type: application/json

{
  "email": "aanltll2992@gmail.com",
  "password": "123",
  "confirmPassword": "123",
  "phoneNumber":"0987654321"
}

###

GET https://anph.xyz/active?t=7%2FWNpDMp5FC7%2BLNOzt7zBBihkYDZDu2tmfrzVSIefcFkI0j7heXUvsbRqgo3RDU9DZuKsSLOjHlWu8uWlTXTURThwUCmd9sLEy%2FJbXK6YReUzURvup6OXjAbrhBSHwaw
Content-Type: application/json

###

POST https://anph.xyz/login
Content-Type: application/json

{
  "email": "aanltll2992@gmail.com",
  "password": "123"
}

###

DELETE https://anph.xyz/logout
Content-Type: application/json

{
  "email": "aanltll2992@gmail.com"
}

###

DELETE https://anph.xyz/detele_account
Content-Type: application/json

{
  "email": "aanltll2992@gmail.com"
}


###

POST https://anph.xyz/token
Content-Type: application/json

{
  "email":"aanltll2992@gmail.com",
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjViMDNiZTExODczMWI2MzFiN2FmODA5ZDVhNzY2YTA3IiwiZW1haWwiOiJhYW5sdGxsMjk5MkBnbWFpbC5jb20iLCJwaG9uZU51bWJlciI6IjA5ODc2NTQzMjEiLCJwYXNzd29yZCI6IjIwMmNiOTYyYWM1OTA3NWI5NjRiMDcxNTJkMjM0YjcwIiwiYWN0aXZlIjp0cnVlLCJpYXQiOjE2NDMxMjQwMTF9.X2ft874jBcQtmGfNlBKTGhH4ZdoeIa1_xl2dNTpmmBo"
}

###

POST https://anph.xyz/user_detail
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjViMDNiZTExODczMWI2MzFiN2FmODA5ZDVhNzY2YTA3IiwiZW1haWwiOiJhYW5sdGxsMjk5MkBnbWFpbC5jb20iLCJwaG9uZU51bWJlciI6IjA5ODc2NTQzMjEiLCJwYXNzd29yZCI6IjIwMmNiOTYyYWM1OTA3NWI5NjRiMDcxNTJkMjM0YjcwIiwiYWN0aXZlIjp0cnVlLCJpYXQiOjE2NDMxMzAzMDcsImV4cCI6MTY0MzEzMzkwN30.h4PhB6NSdTQd9BKX76A15HzxzR9EeqaNmc_PVKgMUSQ



{
  "email": "aanltll2992@gmail.com"
}


###

POST https://anph.xyz/analytics
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjViMDNiZTExODczMWI2MzFiN2FmODA5ZDVhNzY2YTA3IiwiZW1haWwiOiJhYW5sdGxsMjk5MkBnbWFpbC5jb20iLCJwaG9uZU51bWJlciI6IjA5ODc2NTQzMjEiLCJwYXNzd29yZCI6IjIwMmNiOTYyYWM1OTA3NWI5NjRiMDcxNTJkMjM0YjcwIiwiYWN0aXZlIjp0cnVlLCJpYXQiOjE2NDMxNjg1NTcsImV4cCI6MTY0MzE3MjE1N30.l03gdlVEJF_f59X9Ps2qYkcOVwtCThQFXV76XVQr2ZQ


{
  "view_id": "259241289"
}